// prisma/seed.mjs
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const movies = [
  {
    title: "Interstellar",
    genre: "Sci-Fi, Drama",
    synopsis:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    duration: 169,
    director: "Christopher Nolan",
    releaseYear: 2014,
    trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    streamUrl: "https://example.com/interstellar",
    logo: "interstellar_logo.png",
    backdrop: "interstellar_backdrop.jpg",
    poster: "interstellar_poster.jpg",
    rating: 8.6,
  },
  {
    title: "Your Name",
    genre: "Animation, Romance, Fantasy",
    synopsis:
      "Two teenagers share a profound, magical connection upon discovering they are swapping bodies.",
    duration: 106,
    director: "Makoto Shinkai",
    releaseYear: 2016,
    trailer: "https://www.youtube.com/watch?v=xU47nhruN-Q",
    streamUrl: "https://example.com/yourname",
    logo: "yourname_logo.png",
    backdrop: "yourname_backdrop.jpg",
    poster: "yourname_poster.jpg",
    rating: 8.4,
  },
  {
    title: "Spirited Away",
    genre: "Animation, Adventure, Fantasy",
    synopsis:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    duration: 125,
    director: "Hayao Miyazaki",
    releaseYear: 2001,
    trailer: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
    streamUrl: "https://example.com/spiritedaway",
    logo: "spiritedaway_logo.png",
    backdrop: "spiritedaway_backdrop.jpg",
    poster: "spiritedaway_poster.jpg",
    rating: 8.6,
  },
  {
    title: "Parasite",
    genre: "Drama, Thriller",
    synopsis:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    duration: 132,
    director: "Bong Joon Ho",
    releaseYear: 2019,
    trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    streamUrl: "https://example.com/parasite",
    logo: "parasite_logo.png",
    backdrop: "parasite_backdrop.jpg",
    poster: "parasite_poster.jpg",
    rating: 8.5,
  },
  {
    title: "Avengers: Endgame",
    genre: "Action, Sci-Fi, Superhero",
    synopsis:
      "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions.",
    duration: 181,
    director: "Anthony Russo, Joe Russo",
    releaseYear: 2019,
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    streamUrl: "https://example.com/endgame",
    logo: "endgame_logo.png",
    backdrop: "endgame_backdrop.jpg",
    poster: "endgame_poster.jpg",
    rating: 8.4,
  },
  {
    title: "Demon Slayer: Infinity Castle",
    genre: "Animation, Action, Fantasy",
    synopsis:
      "Tanjiro and the Demon Slayer Corps launch a final assault on Muzan Kibutsuji in the Infinity Castle.",
    duration: 120,
    director: "Haruo Sotozaki",
    releaseYear: 2025,
    trailer: "https://www.youtube.com/watch?v=demon_slayer_infinity_castle",
    streamUrl: "https://example.com/demonslayer",
    logo: "demonslayer_logo.png",
    backdrop: "demonslayer_backdrop.jpg",
    poster: "demonslayer_poster.jpg",
    rating: 0.0,
  },
  {
    title: "Dune: Part One",
    genre: "Sci-Fi, Adventure",
    synopsis:
      "Paul Atreides, a brilliant and gifted young man, must travel to the most dangerous planet in the universe.",
    duration: 155,
    director: "Denis Villeneuve",
    releaseYear: 2021,
    trailer: "https://www.youtube.com/watch?v=8g18jFHCLXk",
    streamUrl: "https://example.com/dune",
    logo: "dune_logo.png",
    backdrop: "dune_backdrop.jpg",
    poster: "dune_poster.jpg",
    rating: 8.0,
  },
  {
    title: "Inception",
    genre: "Sci-Fi, Action, Thriller",
    synopsis:
      "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.",
    duration: 148,
    director: "Christopher Nolan",
    releaseYear: 2010,
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    streamUrl: "https://example.com/inception",
    logo: "inception_logo.png",
    backdrop: "inception_backdrop.jpg",
    poster: "inception_poster.jpg",
    rating: 8.8,
  },
  {
    title: "Shutter Island",
    genre: "Mystery, Thriller",
    synopsis:
      "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
    duration: 138,
    director: "Martin Scorsese",
    releaseYear: 2010,
    trailer: "https://www.youtube.com/watch?v=5iaYLCiq5RM",
    streamUrl: "https://example.com/shutterisland",
    logo: "shutterisland_logo.png",
    backdrop: "shutterisland_backdrop.jpg",
    poster: "shutterisland_poster.jpg",
    rating: 8.2,
  },
  {
    title: "Real Steel",
    genre: "Action, Sci-Fi, Drama",
    synopsis:
      "In the near future, robot boxing is a top sport. A struggling promoter feels he's found a champion in a discarded robot.",
    duration: 127,
    director: "Shawn Levy",
    releaseYear: 2011,
    trailer: "https://www.youtube.com/watch?v=O6gmvYqnKcY",
    streamUrl: "https://example.com/realsteel",
    logo: "realsteel_logo.png",
    backdrop: "realsteel_backdrop.jpg",
    poster: "realsteel_poster.jpg",
    rating: 7.0,
  },
  {
    title: "Superman",
    genre: "Action, Adventure, Sci-Fi",
    synopsis:
      "An alien orphan is sent from his dying planet to Earth, where he grows up to become a superhero.",
    duration: 143,
    director: "Richard Donner",
    releaseYear: 1978,
    trailer: "https://www.youtube.com/watch?v=TVh5wAv3bW8",
    streamUrl: "https://example.com/superman",
    logo: "superman_logo.png",
    backdrop: "superman_backdrop.jpg",
    poster: "superman_poster.jpg",
    rating: 7.4,
  },
  {
    title: "Forrest Gump",
    genre: "Drama, Romance",
    synopsis:
      "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man.",
    duration: 142,
    director: "Robert Zemeckis",
    releaseYear: 1994,
    trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    streamUrl: "https://example.com/forrestgump",
    logo: "forrestgump_logo.png",
    backdrop: "forrestgump_backdrop.jpg",
    poster: "forrestgump_poster.jpg",
    rating: 8.8,
  },
  {
    title: "Spider-Man: No Way Home",
    genre: "Action, Sci-Fi, Superhero",
    synopsis:
      "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help, leading to a multiverse crisis.",
    duration: 148,
    director: "Jon Watts",
    releaseYear: 2021,
    trailer: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    streamUrl: "https://example.com/nwh",
    logo: "nwh_logo.png",
    backdrop: "nwh_backdrop.jpg",
    poster: "nwh_poster.jpg",
    rating: 8.2,
  },
  {
    title: "Sore Istri dari Masa Depan",
    genre: "Comedy, Romance, Sci-Fi",
    synopsis:
      "A man receives a letter from his future wife, leading to hilarious and heartwarming consequences.",
    duration: 105,
    director: "Fajar Nugros",
    releaseYear: 2023,
    trailer: "https://www.youtube.com/watch?v=sore_istri_trailer",
    streamUrl: "https://example.com/soreistri",
    logo: "soreistri_logo.png",
    backdrop: "soreistri_backdrop.jpg",
    poster: "soreistri_poster.jpg",
    rating: 7.2,
  },
  {
    title: "The Dark Knight",
    genre: "Action, Crime, Drama",
    synopsis:
      "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests.",
    duration: 152,
    director: "Christopher Nolan",
    releaseYear: 2008,
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    streamUrl: "https://example.com/darkknight",
    logo: "darkknight_logo.png",
    backdrop: "darkknight_backdrop.jpg",
    poster: "darkknight_poster.jpg",
    rating: 9.0,
  },
  {
    title: "Dilan 1990",
    genre: "Romance, Drama",
    synopsis:
      "A teenage boy falls in love with a girl named Dilan in 1990s Bandung, Indonesia.",
    duration: 100,
    director: "Fajar Bustomi",
    releaseYear: 2018,
    trailer: "https://www.youtube.com/watch?v=ZkFz4nN9c8Q",
    streamUrl: "https://example.com/dilan1990",
    logo: "dilan1990_logo.png",
    backdrop: "dilan1990_backdrop.jpg",
    poster: "dilan1990_poster.jpg",
    rating: 7.6,
  },
  {
    title: "Inside Out",
    genre: "Animation, Adventure, Comedy",
    synopsis:
      "After young Riley is uprooted from her Midwest life, her emotions struggle to cope with her new life in San Francisco.",
    duration: 95,
    director: "Pete Docter",
    releaseYear: 2015,
    trailer: "https://www.youtube.com/watch?v=yRUAzGQ3nSY",
    streamUrl: "https://example.com/insideout",
    logo: "insideout_logo.png",
    backdrop: "insideout_backdrop.jpg",
    poster: "insideout_poster.jpg",
    rating: 8.1,
  },
  {
    title: "The Shawshank Redemption",
    genre: "Drama",
    synopsis:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    duration: 142,
    director: "Frank Darabont",
    releaseYear: 1994,
    trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco",
    streamUrl: "https://example.com/shawshank",
    logo: "shawshank_logo.png",
    backdrop: "shawshank_backdrop.jpg",
    poster: "shawshank_poster.jpg",
    rating: 9.3,
  },
  {
    title: "Pulp Fiction",
    genre: "Crime, Drama",
    synopsis:
      "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    duration: 154,
    director: "Quentin Tarantino",
    releaseYear: 1994,
    trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
    streamUrl: "https://example.com/pulpfiction",
    logo: "pulpfiction_logo.png",
    backdrop: "pulpfiction_backdrop.jpg",
    poster: "pulpfiction_poster.jpg",
    rating: 8.9,
  },
  {
    title: "Whiplash",
    genre: "Drama, Music",
    synopsis:
      "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.",
    duration: 106,
    director: "Damien Chazelle",
    releaseYear: 2014,
    trailer: "https://www.youtube.com/watch?v=7d_jQycdQGo",
    streamUrl: "https://example.com/whiplash",
    logo: "whiplash_logo.png",
    backdrop: "whiplash_backdrop.jpg",
    poster: "whiplash_poster.jpg",
    rating: 8.5,
  },
];

async function main() {
  console.log("Seeding movies...");
  await prisma.movie.createMany({ data: movies, skipDuplicates: true });
  console.log("Seeding done.");
}

await main()
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
