contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Hoseki DevOps Blog"
canonifyurls  = true

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  dateFormat = "April 17, 2004"
  commit = false
  rss = false

[Author]
  name = "Farid Zahran"
