GET http://localhost:5000/products

###
GET http://localhost:5000/products/5

###
POST http://localhost:5000/products
Content-Type: application/json

{
  "title": "Inno X3 Pro",
  "price": 650000,
  "realPrice": 799000,
  "description": "Symmetrical gaming wireless mouse for esports.",
  "variant": "White",
  "category": "Mouse",
  "image": "/images/products/mouse-inno-x3-pro.jpg"
}

###
PATCH http://localhost:5000/products/16
Content-Type: application/json

{
  "title": "Inno X3 Pro Max",
  "price": 570000,
  "realPrice": 799000,
  "description": "Symmetrical gaming 4K hz wireless 2.4 ghz and bluetooth mouse for competitive and esports scene.",
  "variant": "Black",
  "category": "Mouse",
  "image": "https://bimg.akulaku.net/goods/spu/6bc80b581bf043dc804f922f7207b6180112.jpg?w=726&q=80&fit=1"
}

###
DELETE http://localhost:5000/products/16
